# Generated by Django 4.0.6 on 2022-07-12 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coffee', to='coffee_journal.user'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='brew_method',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='origin',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='roast',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='brew_method',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
