# Generated by Django 4.0.6 on 2022-07-12 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_journal', '0003_remove_user_name_user_username_alter_coffee_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
